### ISSUE TITLE
Errors with Swift 5.0 -- Extraneous argument label 'where:' in call

### ISSUE THREAD

**Issue by Mozahler** [vincent-pradeilles/KeyPathKit#18]
What an awesome library!! Hats off to you 🎩
Some of the tests fail under Swift 5.0 (10 lines in filterLessTests.swift have errors)
I'll see if I can figure it out, but meantime here's what I know...

I'm getting this message: Extraneous argument label 'where:' in call
for these lines from class FilterLessTests: XCTestCase

        XCTAssertTrue(data.filter(where: \.int < 2).isEmpty)
        XCTAssertTrue(data.filter(where: \.double < 2.0).isEmpty)

        XCTAssertEqual(data.filter(where: \.int < 200), data)
        XCTAssertEqual(data.filter(where: \.int <= 100), data)
        XCTAssertEqual(data.filter(where: \.double < 6e4), data)
        XCTAssertEqual(data.filter(where: \.double <= 5e4), data)

        XCTAssertEqual(data.filter(where: \.int < 100), [TestData(int: 3, double: 4.5), TestData(int: -2, double: 5e4)])
        XCTAssertEqual(data.filter(where: \.double < 100.0), [TestData(int: 3, double: 4.5), TestData(int: 100, double: -2300)])

        XCTAssertEqual(data.filter(where: \.int < -5), [])
        XCTAssertEqual(data.filter(where: \.double <= -2301), [])

These lines all test ok under Swift 4.2

**Comment by vincent-pradeilles** [comment]
Thanks for your input, I’ll make sure to check it out!

Could you let me know in which commit I can reproduce the issue?

**Comment by Mozahler** [comment]
Actually, it looks like I've done something wrong. 
I had somehow added an import to my main project in the test file.
I can't believe you responded in under 10 minutes!
Sorry for the false alarm. I'm closing this.
thanks for all your hard work!  🍀

**Comment by Mozahler** [comment]
User induced error.
🎉👯‍♂️
